// src/components/pages/Heroes/Heroes.tsx
import classNames from 'classnames';
import heroesJson from 'dotaconstants/build/heroes.json';
import { FC } from 'react';
import Card from 'src/components/atoms/Card';
import HeroIcon from 'src/components/atoms/HeroIcon';
import styles from './Heroes.module.scss';

const ATTRIBUTES = ['Strength', 'Agility', 'Intelligence'];

const Heroes: FC = () => (
  <div className={classNames('container', styles.container)}>
    {ATTRIBUTES.map((attribute) => (
      <Card key={attribute} title={attribute}>
        {Object.values(heroesJson)
          .filter(
            (hero) =>
              hero.primary_attr === attribute.substr(0, 3).toLowerCase(),
          )
          .sort((heroA, heroB) =>
            heroA.localized_name.localeCompare(heroB.localized_name),
          )
          .map((hero) => (
            <HeroIcon id={hero.id} key={hero.id} />
          ))}
      </Card>
    ))}
  </div>
);

export default Heroes;

// src/views/Heroes.vue
<template>
  <div class="container my-5">
    <h1>Heroes</h1>

    <HeroList title="Strength" :filter="attributeHeroes('str')" type="portrait"/>
    <HeroList title="Agility" :filter="attributeHeroes('agi')" type="portrait"/>
    <HeroList title="Intelligence" :filter="attributeHeroes('int')" type="portrait"/>
  </div>
</template>

<script lang="ts">
import heroes from 'dotaconstants/build/heroes.json';
import { Component, Vue } from 'vue-property-decorator';

import HeroList from '@/components/heroes/HeroList.vue';
import Hero from '@/interfaces/Hero';

@Component({
  components: {
    HeroList,
  },
})
export default class Heroes extends Vue {
  private attributeHeroes(attribute: string) {
    return (data: Hero) => data.primary_attr === attribute;
  }
}
</script>
