// src/components/core/Footer.vue
<template>
  <footer>
    <div class="container">
      <p>
        Copyright &copy; 2018 Dávid Richolm
      </p>
      <p>
        Dota 2 is a registered trademark of Valve Corporation.
        <br>This site and service are not related in any way to Valve Corporation.
      </p>
      <router-link to="/about">About</router-link>
      &middot;
      <a href="https://github.com/dricholm/guess-the-hero">GitHub</a>
    </div>
  </footer>
</template>

<style lang="scss" scoped>
footer {
  background-color: rgba(0, 0, 0, 0.2);
  color: #bbb;
  font-size: $font-size-sm;
  padding: 3rem 0;
}
</style>

// src/components/atoms/Footer/Footer.tsx
import classNames from 'classnames';
import Link from 'next/link';
import { FC } from 'react';
import styles from './Footer.module.scss';

const Footer: FC = () => (
  <footer className={styles.container}>
    <div className={classNames('container', styles.content)}>
      <ul className={styles.list}>
        <li>
          <Link href="/about">
            <a>About</a>
          </Link>
        </li>
        <li>
          <Link href="https://github.com/dricholm/guess-the-hero">
            <a>GitHub</a>
          </Link>
        </li>
      </ul>
      <p className={styles.text}>
        Dota 2 is a registered trademark of Valve Corporation.
        <br />
        This site and service are not related in any way to Valve Corporation.
      </p>
    </div>
  </footer>
);

export default Footer;
