// src/components/molecules/ItemList/ItemList.tsx
import { FC } from 'react';
import Card from 'src/components/atoms/Card';
import ItemWithModal from '../ItemWithModal';
import styles from './ItemList.module.scss';

interface Props {
  ids: Array<number>;
  title: string;
}

const ItemList: FC<Props> = ({ ids, title }) => (
  <Card title={title}>
    <div className={styles.container}>
      {ids.map((id) => (
        <ItemWithModal id={id} key={id} />
      ))}
    </div>
  </Card>
);

export default ItemList;

// src/components/ItemList.vue
<template>
  <div class="mb-4">
    <h2 v-if="title">
      {{ title }}
    </h2>

    <ItemIcon :id="itemId" v-for="itemId in ids" :key="itemId"/>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import ItemIcon from '@/components/ItemIcon.vue';

@Component({
  components: {
    ItemIcon,
  },
})
export default class ItemList extends Vue {
  @Prop(String) private title!: string;
  @Prop({ default: () => [], type: Array })
  private ids!: number[];
}
</script>
